# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  # hosts
  - &stendarr age18vqcm9eh9r8r4f8m96cgxnza2fsr2d3sm4kknlr320qy9z27g5jqgszr7z
  - &auri-el age1zkzt2gqrddkwvlk7gygpvgnft8ldg6urfjl0se0x2rjm20dg497qy7hzwl
  
  # users
  - &dallinchi age1gwqe6x8ef5dxy9v4uyerr4dh5sw78mauhayxdz5p8elh8gpjm3nqty4jf0

creation_rules:
  - path_regex: secrets/users.yaml$
    key_groups:
    - age:
      - *dallinchi
      - *stendarr
      - *auri-el

  - path_regex: secrets/vpn.yaml$
    key_groups:
    - age:
      - *dallinchi
      - *stendarr
      - *auri-el
