#!/usr/bin/env bash

caelestia shell drawers toggle bar

# if pgrep -x ".quickshell-wra" > /dev/null
# then
#     pkill quickshell
#     # echo "quickshell off"
# else
#     echo "quickshell on"
#     quickshell -c ~/.config/quickshell/lacrity-space &
# fi
