#!/usr/bin/env python3

import subprocess
import re

def get_active_sink():
    result_info = subprocess.run(['pactl', 'info'], capture_output=True, text=True)
    result_sink = subprocess.run(['pactl', 'list', 'sinks'], capture_output=True, text=True)
    
    if result_sink.returncode != 0:
        print("Ошибка при выполнении команды pactl.")
        return
    
    output_info = result_info.stdout.splitlines()
    output_sink = result_sink.stdout.splitlines()
   
    name = ""
    for line in output_info:
        if "Default Sink:" in line:
            name = line.split(":")[1].strip()
            break

    running_state = False
    active_port = None
    for line in output_sink:
        if not running_state:
            if name in line:
                running_state = True
            continue

        if "Active Port" in line:
            active_port = line.split(":")[1].strip()
            break
    
    if active_port:
        print(active_port)
    else:
        print("Не удалось определить активное устройство вывода звука.")

if __name__ == "__main__":
    get_active_sink()

