#!/usr/bin/env python3

import re
import subprocess
from os import system

def get_transform():
    output = subprocess.run(['hyprctl', 'monitors'], capture_output=True, text=True)
    pattern = r"Monitor HDMI-A-1 \(ID 1\):\n.*transform: (\d)"
    match = re.search(pattern, output.stdout.strip(), re.DOTALL)

    if match:
        transform_value = int(match.group(1))
        print(transform_value)

        return transform_value

def get_size():
    output = subprocess.run(['hyprctl', 'monitors'], capture_output=True, text=True)
    pattern = r'at (\d+)x\d+'
    match = re.search(pattern, output.stdout.strip(), re.DOTALL)
    
    if match:
        size_value = int(match.group(1))
        print(size_value)
        return size_value
    
if get_transform():
    if get_size() == 1920:
        system('hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 1" | hyprctl keyword monitor "eDP-1, 1920x1080, 900x360,1"')
    else:
        system('hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 1" | hyprctl keyword monitor "eDP-1, 1920x1080, 1920x0,1"')

else:
    if get_size() == 1920:
        system('hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 0" | hyprctl keyword monitor "eDP-1, 1920x1080, 1440x0,1"')
    else:
        system('hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 0" | hyprctl keyword monitor "eDP-1, 1920x1080, 1920x0,1"')


#  hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 1" | hyprctl keyword monitor "eDP-1, 1920x1080, 1920x0,1
