#!/usr/bin/env python3

import subprocess
from optparse import OptionParser

parser = OptionParser()
opts, args = parser.parse_args()

result = subprocess.run(["hyprctl", "clients"], capture_output=True, text=True)
window_data = result.stdout
windows = window_data.strip().split("\n\n")
workspace_dict = {}

for window in windows:
    lines = window.splitlines()
    workspace_number = ""
    floating = ""

    for line in lines:
        if "workspace:" in line:
            workspace_number = line.split(":")[1].strip().split()[0]

        if "floating:" in line:
            floating = line.split(":")[1].strip()
            break

    if workspace_number not in workspace_dict:
        workspace_dict[workspace_number] = []
    workspace_dict[workspace_number].append(floating)

def get_status():
    if workspace_dict.get(args[0]) == None:
        return "empty"
    elif len(workspace_dict.get(args[0])) > 1:
        if workspace_dict.get(args[0]).count('0') == 1:
            return "solo"
        else:
            return "default"
    elif len(workspace_dict.get(args[0])) == 1 and '0' not in workspace_dict.get(args[0]):
        return "default"
    elif len(workspace_dict.get(args[0])) == 1 and '1' not in workspace_dict.get(args[0]):
        return "solo"

if __name__ == "__main__":
    print(get_status())
#    for ws, windows in workspace_dict.items():
#        print(f"Workspace {ws}: {len(wo
