#!/usr/bin/env python3

'''
Скрипт ищет первый моник в выводе niri msg outputs, и ищет его позиционирование, если оно 1920 (стыкуется с главным моником) то отсоединяет его (позиция 0 по X)

Если нужен конкретный моник, нужно допиливать.
'''

import re
import subprocess
from os import system

def get_size():
    output = subprocess.run(['niri', 'msg', 'outputs'], capture_output=True, text=True)
    pattern = r'Logical position: (\d+), \d+'
    match = re.search(pattern, output.stdout.strip(), re.DOTALL)
    
    if match:
        size_value = int(match.group(1))
        return size_value
    
if get_size() == 1920:
    system('niri msg output "DVI-D-1" position set 0 0')
else:
    system('niri msg output "DVI-D-1" position set 1920 0')

#
# else:
#     if get_size() == 1920:
#         system('hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 0" | hyprctl keyword monitor "eDP-1, 1920x1080, 1440x0,1"')
#     else:
#         system('hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 0" | hyprctl keyword monitor "eDP-1, 1920x1080, 1920x0,1"')
#
#  hyprctl keyword monitor "HDMI-A-1, 1440x900, 0x0, 1, transform, 1" | hyprctl keyword monitor "eDP-1, 1920x1080, 1920x0,1
